### ISSUE TITLE
Performance improvement in Category callAppenders()

### ISSUE THREAD

**Issue by lauredogit** [qos-ch/reload4j#51]
Hi,

We just got a bottleneck in production with 2000+ threads blocked waiting on the lock in the synchronized block of callAppenders() in Category.

This never happend before to us, including in stress tests.

However, I seem to think a small performance improvement could be made with a simple outer call (if I'm reading the code correctly).

`    public void callAppenders(LoggingEvent event) {
	int writes = 0;

	for (Category c = this; c != null; c = c.parent) {
	    // Protected against simultaneous call to addAppender, removeAppender,...
        // outer call, read the values under lock:
        AppenderAttachableImpl aai;
        boolean additive;
	    synchronized (c) {
            aai = c.aai;
            additive = c.additive;
        }
        // outer call
        if (aai != null) {
            writes += aai.appendLoopOnAppenders(event);
        }
        if (!additive) {
            break;
        }
    }`

Since aai is final and is a thread-safe data structure, we only want correct visibility of the aai and additive values and we don't need to block the whole category object.

What do you think?

Best regards,
Dominique

**Comment by ceki** [comment]
@lauredogit Which version of reload4j are you using?

**Comment by lauredogit** [comment]
I'm using 1.21

**Comment by lauredogit** [comment]
It appears the threads were piling up due to slowness induced by a remote diagnostic agent running at the time (RDA).

It is strange that it materialized by showing a bottleneck in the synchronized block of **_Category#callAppenders()_**.

Nonetheless, it might be a performance improvement to use an open call to invoke the appendLoopOnAppenders(...) method instead of doing it while holding the lock.

**Comment by isoflavone-r** [comment]
hello.  FWIW i'm also running into thread pileup on with reload4j  1.2.25 in an Apache Spark 3.0.1 application used from `pyspark` that i don't see w/ vanilla log4j on the same task.  jdk 8  (but also tested 11).   I'm not aware of any VM debug agents attached / running.   (there's maybe some excess info below for  search engines / anyone else that might walk this way) 


Symptoms are that on a VM with 56 cores the application has long periods (maybe 90% of wall-clock runtime in aggregate) of only using 6 cores compared to the same tasks on stock Spark 3.0.1 which is using 50+ cores. Overall impact is that elapsed time for the task is ~8 hours vs 1.5 hours.

based on `jstack` output during this period there are many threads  (25+) waiting on  [at org.apache.log4j.Category.callAppenders(Category.java:192)](https://github.com/qos-ch/reload4j/blob/63d44e1c7eb0494688dc8e5cc2fe9ae0809c5c1d/src/main/java/org/apache/log4j/Category.java#L192C13-L192C31)  

the stacks look something like this:
```  
"Executor task launch worker for task 2565" #4463 daemon prio=5 os_prio=0 cpu=76064.28ms elapsed=322.80s tid=0x00007ef054009800 nid=0x8d664 waiting for monitor entry  [0x00007eef32  5bd000]
     java.lang.Thread.State: BLOCKED (on object monitor)
          at org.apache.log4j.Category.callAppenders(Category.java:192)
          - waiting to lock <0x00007ef35c5677f0> (a org.apache.log4j.spi.RootLogger)
          at org.apache.log4j.Category.forcedLog(Category.java:364)
          at org.apache.log4j.Category.log(Category.java:771)
          at org.slf4j.impl.Reload4jLoggerAdapter.debug(Reload4jLoggerAdapter.java:252)
          at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.log(MessageColumnIO.java:283)
```

In my app's case parquet writing  as part of 
```        
          at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:128)
          at org.apache.parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:182)
          at org.apache.parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:44)
```

and in our setup i note that we use just the spark deployment so it says the following at startup:
> 24/10/12 02:45:44 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

(idk if the above can be bypassed by installing native package by installing a matching hadoop  and setting HADOOP_HOME. 
( may attempt that )  )
